Week-2 - Add realization for the primal mathematical operations
BrannB/scala-course-2021-autumn pull request #2
Opened 2021-12-19 11:07 UTC by BrannB

2021-12-23 19:34 UTC, IgorWolkov commented on src/main/scala/karazin/scala/users/group/week2/homework/Homework.scala
> +        then null
It's forbidden to use `null` in Scala. As it was said you can throw meaningful exception in case of zero.

2021-12-23 19:35 UTC, IgorWolkov requested changes
You need to provide test for the code.

2021-12-23 19:35 UTC, IgorWolkov commented on src/main/scala/karazin/scala/users/group/week2/homework/Homework.scala
> +      new Rational((-1) * this.numer, this.denom)
You can use `-this.numer` instad.

2021-12-23 19:38 UTC, IgorWolkov commented on src/main/scala/karazin/scala/users/group/week2/homework/Homework.scala
> +    override def equals(other: Any): Boolean = other match {
Every time you implement `equals` you have to implement `hashCode`.
https://www.baeldung.com/java-equals-hashcode-contracts
https://alvinalexander.com/scala/how-to-define-equals-hashcode-methods-in-scala-object-equality/

2021-12-23 19:39 UTC, IgorWolkov commented on src/main/scala/karazin/scala/users/group/week2/homework/Homework.scala
> +      case that: Rational => (denom == that.denom) && (g == that.g) && (numer == that.numer) && (that.isInstanceOf[Rational])
You call `g == that.g` before you check that `that` is `Rational`.

2021-12-24 11:09 UTC, IgorWolkov requested changes
The same I do not see the committed file for tests.

2021-12-25 12:00 UTC, BrannB commented
@IgorWolkov I added tests and fix your issues. Please, review my changes.

2021-12-25 21:29 UTC, IgorWolkov commented on src/main/scala/karazin/scala/users/group/week2/homework/Homework.scala
> +      new Rational(that.numer * this.denom + that.denom * this.numer, that.denom * this.denom)
Please get rid of `new`. Everywhere. Even in tests.

2021-12-25 21:29 UTC, IgorWolkov commented on src/main/scala/karazin/scala/users/group/week2/homework/Homework.scala
> +      new Rational(that.denom * this.numer - that.numer * this.denom, that.denom * this.denom)
What about unary minus?

2021-12-25 21:30 UTC, IgorWolkov requested changes
Almost done.

2021-12-26 08:54 UTC, merged